apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 3kube   # Change as needed
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: ganesh02004/secure_flask_app:latest # <--- Replace this
        ports:
        - containerPort: 5000  # <--- Update if different
