apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer  # Change to ClusterIP or NodePort if needed
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # <--- Should match containerPort above
